// Starter curated system content for Lingua's global content library.
// These records are recommendation-ready and transcript-ready, but they are
// not trusted vocabulary/sentence truth and do not imply validated transcript truth.

const STARTER_CONTENT_SEED_SOURCE = 'starter_content_v1';

const STARTER_CONTENT_ITEMS = Object.freeze([
  {
    title: '０から始める日本語 日常会話！【Video for very beginners】Basic conversation in JAPANESE. Japanese Listening Practice',
    sourceType: 'video',
    sourceProvider: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=IJEn-9nAFQE',
    sourceId: 'IJEn-9nAFQE',
    language: 'ja',
    difficulty: 'beginner',
    topicTags: ['daily_conversation', 'greetings'],
    registerTags: ['mixed'],
    skillTags: ['listening', 'vocabulary'],
    transcriptStatus: 'manual_ready',
    transcriptSource: 'manual',
    isSystemContent: true,
    isCurated: true,
    visibility: 'global',
    seedSource: STARTER_CONTENT_SEED_SOURCE
  },
  {
    title: 'Learn How to Introduce Yourself in Japanese | Can Do #1',
    sourceType: 'video',
    sourceProvider: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=NwZzGbzi_jY',
    sourceId: 'NwZzGbzi_jY',
    language: 'ja',
    difficulty: 'beginner',
    topicTags: ['self_intro', 'daily_conversation'],
    registerTags: ['polite'],
    skillTags: ['listening', 'speaking'],
    transcriptStatus: 'manual_ready',
    transcriptSource: 'manual',
    isSystemContent: true,
    isCurated: true,
    visibility: 'global',
    seedSource: STARTER_CONTENT_SEED_SOURCE
  },
  {
    title: '25 Japanese Words and Phrases for Beginners',
    sourceType: 'video',
    sourceProvider: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=D-uNsJU6Nl0',
    sourceId: 'D-uNsJU6Nl0',
    language: 'ja',
    difficulty: 'beginner',
    topicTags: ['survival_phrases', 'vocabulary'],
    registerTags: ['mixed'],
    skillTags: ['listening', 'vocabulary', 'speaking'],
    transcriptStatus: 'manual_ready',
    transcriptSource: 'manual',
    isSystemContent: true,
    isCurated: true,
    visibility: 'global',
    seedSource: STARTER_CONTENT_SEED_SOURCE
  },
  {
    title: '#9 Verb Masu (Polite) form ます形┃Japanese Lesson for Absolute Beginners',
    sourceType: 'video',
    sourceProvider: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=nZXZElTzWjY',
    sourceId: 'nZXZElTzWjY',
    language: 'ja',
    difficulty: 'beginner',
    topicTags: ['grammar', 'daily_conversation'],
    registerTags: ['polite'],
    skillTags: ['listening', 'speaking'],
    transcriptStatus: 'manual_ready',
    transcriptSource: 'manual',
    isSystemContent: true,
    isCurated: true,
    visibility: 'global',
    seedSource: STARTER_CONTENT_SEED_SOURCE
  },
  {
    title: 'Essential Japanese Travel Phrases (+ Grammar)',
    sourceType: 'video',
    sourceProvider: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=xHMAq9x2cEY',
    sourceId: 'xHMAq9x2cEY',
    language: 'ja',
    difficulty: 'beginner_intermediate',
    topicTags: ['survival_phrases', 'directions', 'travel'],
    registerTags: ['polite'],
    skillTags: ['listening', 'speaking', 'vocabulary'],
    transcriptStatus: 'manual_ready',
    transcriptSource: 'manual',
    isSystemContent: true,
    isCurated: true,
    visibility: 'global',
    seedSource: STARTER_CONTENT_SEED_SOURCE
  },
  {
    title: 'Real Casual Japanese Conversation | Roommates at the Supermarket (Beginner Listening Practice)',
    sourceType: 'video',
    sourceProvider: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=U26OiajUkSU',
    sourceId: 'U26OiajUkSU',
    language: 'ja',
    difficulty: 'beginner_intermediate',
    topicTags: ['shopping', 'daily_conversation', 'food'],
    registerTags: ['casual'],
    skillTags: ['listening', 'vocabulary'],
    transcriptStatus: 'manual_ready',
    transcriptSource: 'manual',
    isSystemContent: true,
    isCurated: true,
    visibility: 'global',
    seedSource: STARTER_CONTENT_SEED_SOURCE
  },
  {
    title: '【N5-N4】Easy Japanese conversation - Meeting with friends',
    sourceType: 'video',
    sourceProvider: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=Xr1ftwpDIvE',
    sourceId: 'Xr1ftwpDIvE',
    language: 'ja',
    difficulty: 'beginner_intermediate',
    topicTags: ['daily_conversation', 'hobbies', 'social'],
    registerTags: ['casual'],
    skillTags: ['listening', 'speaking'],
    transcriptStatus: 'manual_ready',
    transcriptSource: 'manual',
    isSystemContent: true,
    isCurated: true,
    visibility: 'global',
    seedSource: STARTER_CONTENT_SEED_SOURCE
  },
  {
    title: '【N5-N4】Ep255 How to spend your days off / Japanese podcast for beginners',
    sourceType: 'video',
    sourceProvider: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=yqksKKSkjhQ',
    sourceId: 'yqksKKSkjhQ',
    language: 'ja',
    difficulty: 'beginner_intermediate',
    topicTags: ['daily_life', 'hobbies', 'listening_practice'],
    registerTags: ['casual'],
    skillTags: ['listening'],
    transcriptStatus: 'manual_ready',
    transcriptSource: 'manual',
    isSystemContent: true,
    isCurated: true,
    visibility: 'global',
    seedSource: STARTER_CONTENT_SEED_SOURCE
  },
  {
    title: '【N5-N3】Easy Japanese Conversation with Miku Real Japanese (Miku)',
    sourceType: 'video',
    sourceProvider: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=u8Z2Ec5y_9o',
    sourceId: 'u8Z2Ec5y_9o',
    language: 'ja',
    difficulty: 'intermediate',
    topicTags: ['daily_conversation', 'listening_practice'],
    registerTags: ['mixed'],
    skillTags: ['listening', 'speaking'],
    transcriptStatus: 'manual_ready',
    transcriptSource: 'manual',
    isSystemContent: true,
    isCurated: true,
    visibility: 'global',
    seedSource: STARTER_CONTENT_SEED_SOURCE
  },
  {
    title: 'Japanese for Absolute Beginners: Master the Basics in Under ...',
    sourceType: 'video',
    sourceProvider: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=FgCPc5qPCh0',
    sourceId: 'FgCPc5qPCh0',
    language: 'ja',
    difficulty: 'beginner',
    topicTags: ['greetings', 'survival_phrases', 'daily_conversation'],
    registerTags: ['mixed'],
    skillTags: ['listening', 'vocabulary'],
    transcriptStatus: 'manual_ready',
    transcriptSource: 'manual',
    isSystemContent: true,
    isCurated: true,
    visibility: 'global',
    seedSource: STARTER_CONTENT_SEED_SOURCE
  }
]);

module.exports = {
  STARTER_CONTENT_ITEMS,
  STARTER_CONTENT_SEED_SOURCE
};
